// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArS7PBHicxoLvmQq1FKtcmOrO9pnnUiEQ',
    appId: '1:894765241434:web:d346d82ba91557ffb23463',
    messagingSenderId: '894765241434',
    projectId: 'my-notes-flutter-app',
    authDomain: 'my-notes-flutter-app.firebaseapp.com',
    storageBucket: 'my-notes-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO16V7LT13-wUcuGV-Ro3SMX8Scqs6omk',
    appId: '1:894765241434:android:e0cda7fe8ed27e28b23463',
    messagingSenderId: '894765241434',
    projectId: 'my-notes-flutter-app',
    storageBucket: 'my-notes-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_KhoFL_U_2PJb-6X6XnnZVdUh9YCOjXE',
    appId: '1:894765241434:ios:36d59e8c1870c646b23463',
    messagingSenderId: '894765241434',
    projectId: 'my-notes-flutter-app',
    storageBucket: 'my-notes-flutter-app.appspot.com',
    iosClientId: '894765241434-57qd3l7vpampubq3sgd6no4dl323ieb4.apps.googleusercontent.com',
    iosBundleId: 'com.karim.mynotes',
  );
}
